use zplugin

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -1,34 +1,60 @@
-source ~/dotfiles/zsh/functions/functions.zsh
+# vim:ft=zsh:
+# setopt warn_create_global
 
-################################################################################
-# Antibody setup
-################################################################################
+### ZPLUGIN
+local __ZPLUGIN="${ZDOTDIR:-$HOME}/.zplugin/bin/zplugin.zsh"
 
-# From oh-my-zsh
-export ZSH="$(antibody home)/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh"
-DISABLE_AUTO_UPDATE="true"
+if [[ ! -f "$__ZPLUGIN" ]]; then
+  if (( $+commands[curl] )); then
+    sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"
+  else
+    echo 'curl not found' >&2
+    exit 1
+  fi
+fi
 
-source <(antibody init)
-antibody bundle < ~/dotfiles/zsh/plugins.txt
-#source ~/dotfiles/zsh/zsh_plugins.sh
+source "$__ZPLUGIN"
+autoload -Uz _zplugin
+(( ${+_comps} )) && _comps[zplugin]=_zplugin
 
-alias 'ra'='antibody bundle \
-            < ~/dotfiles/zsh/plugins.txt \
-            > ~/dotfiles/zsh/zsh_plugins.sh && \
-            antibody update'
-
-
-# enable completion features
-fpath=(~/.zsh/completion $fpath)
-autoload -Uz compinit && compinit -i
-
-# allow .hidden file tab completion
-setopt globdots
+###
 
 
-# required to find some shared libs
-export LD_LIBRARY_PATH=/usr/local/lib
+# Utility {{{
+zplugin ice wait lucid
+zplugin light https://github.com/zsh-users/zsh-history-substring-search
 
-####################
+zplugin load zdharma/history-search-multi-word
 
-source ~/dotfiles/zsh/aliases/docker.zsh
+zplugin ice wait lucid atload"_zsh_autosuggest_start"
+zplugin light https://github.com/zsh-users/zsh-autosuggestions
+export ZSH_AUTOSUGGEST_USE_ASYNC=true
+
+zplugin ice wait lucid atinit"zpcompinit; zpcdreplay"
+zplugin light https://github.com/zdharma/fast-syntax-highlighting
+
+zplugin ice wait lucid
+zplugin light https://github.com/djui/alias-tips
+
+zplugin ice wait blockf lucid
+zplugin light https://github.com/zsh-users/zsh-completions
+
+# }}}
+
+# Shell {{{
+zplugin light zdharma/zui
+
+zplugin ice pick"async.zsh" src"pure.zsh"
+zplugin light https://github.com/ahmedelgabri/pure
+
+# }}}
+# Prezto {{{
+zplugin ice svn
+zplugin snippet PZT::modules/docker
+
+zplugin ice svn 
+zplugin snippet PZT::modules/helper
+
+zplugin ice svn 
+zplugin snippet PZT::modules/git
+# }}}
